### ISSUE TITLE
Nothing happened: only empty tag

### ISSUE THREAD

**Issue by lgXenos** [prokhonenkov/yii2-banners-system#1]
Hi
String 
`<?= \prokhonenkov\bannerssystem\BannerZone::getInstance()->setZoneById(1);?>`
Generate html:
`<div class="banner_zone_1 banner-system hidden "><div class="veil"></div></div>`
And what now?

Where is my banner?

_Если говоришь по-русски: то я сделал банер, зону, вставил код, получил пустышку, JS подключились, область не заполнилась._

**Comment by lgXenos** [comment]
![image](https://user-images.githubusercontent.com/14957311/79143800-86fdd480-7dc6-11ea-803d-3685ff33f0ac.png)
![image](https://user-images.githubusercontent.com/14957311/79143856-9d0b9500-7dc6-11ea-94e3-851cd8f12ca6.png)
![image](https://user-images.githubusercontent.com/14957311/79143902-b3195580-7dc6-11ea-98a4-6216a5aaf0de.png)

**Comment by prokhonenkov** [comment]
Make sure what you correct to configure of the plugin. Here video about how to create banner https://www.dropbox.com/s/xzih0uq8w3vj5cn/vokoscreen-2020-04-14_09-13-33.mp4?dl=0.

**Comment by lgXenos** [comment]
В общем меня сбил параметр "Show on specified pages only"
Т.к. я рассматривал вариант, когда банер должен показывать сквозным путем, то я не заполнил его. Т.к. расчитывал, что отсутствие параметра == значению "везде"

Попутно: очень странно, что банерная система:
1. Тянет внешний JS с левого хостинга
2. Подключает форсировано бутстрап на фронте

Второй момент: после того, как банер отобразился - я не могу войти в редактирование существующего банера
Ты ищешь папку vendor в текущем APP, а надо - в корне проекта в целом. Специфика шаблона advanced
![image](https://user-images.githubusercontent.com/14957311/79198177-bd296b80-7e3b-11ea-83a5-b4bfc4bb47a3.png)

**Comment by prokhonenkov** [comment]
Выкатил новый релиз с исправлениями.
